### ISSUE TITLE
Add disabled placeholder links in sidebar

### ISSUE THREAD

**Issue by weiseng18** [opengovsg/starter-kit#106]
**Is your feature request related to a problem? Please describe.**

Want to add disabled placeholder buttons in `Sidebar`, possibly something like this

https://github.com/opengovsg/starter-kit/assets/20338724/e56d99f5-9bbd-4926-a4be-da4b3b44267b

**Describe the solution you'd like**

Mainly just sharing that this is how I got it to work! But maybe the following props could be a constant somewhere, so developers can just import and use

**Describe alternatives you've considered**

My current implementation is to pass these props to `Sidebar`

```js
{
  props: {
    as: Tag,
    bgColor: 'neutral.whiteLilac',
    href: {},
    _hover: {},
    _active: {},
    fontWeight: 400, // or whatever the default is, because Tag may change
    cursor: 'not-allowed',
  }
}
```

- `Tag` is needed instead of `Text`, because `Text` renders as `<p>` and it would lead to rendering a `<p>` within a `<p>`
- The rest of the properties help to make the button appear as if it has been disabled

**Comment by karrui** [comment]
sorry for the late reply. This is now in ogp's design system via this PR: https://github.com/opengovsg/design-system/pull/351
