### ISSUE TITLE
Error on running database migrations

### ISSUE THREAD

**Issue by handshou** [opengovsg/starter-kit#163]
**Describe the bug**
Schema drift is causing a Prisma issue, preventing making tweaks to the schema and generating new migrations with the command `npm run migrate:dev`

**To Reproduce**
1. Use a fresh copy of starter-kit, click Use this template > Create a new repository.
2. Clone repository to local machine.
3. Install packages `npm install`
4. Copy .env.example to .env.development.local
5. Start Prisma database locally  `docker compose -f docker-compose.yml up -d --wait`
6. Simulate new feature and small schema change, but in this case make no schema changes, lets test if migrations run at all.
7. Run database migrations `export $(grep DATABASE_URL .env.development.local | xargs) && npm run migrate:dev`
8. See error
```bash
Error: db error: ERROR: internal error: executing declarative schema change Statement
Phase stage 1 of 1 with 98 MutationType ops (rollback=false) for DROP DATABASE: error executing Statement
Phase stage 1 of 1 with 98 MutationType ops: relation "Post" (251): origin table "ReadPosts" (252) is dropped
DETAIL: • Schema change plan for DROP DATABASE IF EXISTS ‹"prisma_migrate_shadow_db_cb9338af-2ed5-4c49-9adc-325e900d0bc1"›;
```

**Expected behavior**
Be able to sync migrations and Prisma database with `npm run migrate:dev`. See screenshot below.

**Screenshots**
Happy flow scenario.
<img width="837" alt="Screenshot 2023-07-13 at 5 55 35 PM" src="https://github.com/opengovsg/starter-kit/assets/12982599/2c8f8217-a706-46a7-8b8d-09b3dc565e0c">

Error screenshot.
<img width="1912" alt="Screenshot 2023-07-13 at 5 49 55 PM" src="https://github.com/opengovsg/starter-kit/assets/12982599/ca49ff76-c544-43a2-9dfc-e06825199d5c">

Following starter-kit instruction.
<img width="1912" alt="Screenshot 2023-07-13 at 5 42 45 PM" src="https://github.com/opengovsg/starter-kit/assets/12982599/d9610436-2ce5-47bf-a08b-b3068475ecce">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4
 - Docker desktop 4.20.1 (110738)
 - Docker Compose v2.18.1
 - Prisma v4.15.0

**Additional context**
When I found the solution, which is adding Prisma shadow database for generating migrations after a schema drift, I realised I did not fully understand what I was doing wrong - but the solution worked and I could make schema changes.

Next, I ran a blame on file `.env.example` line 16, and found a shadow database env variable existed, but was cleaned up.
I don't fully understand why. Link to git blame: https://github.com/opengovsg/starter-kit/commit/15dc8520b0ff292366090ac55c597d43661a6bc9

**Am I doing migrations wrongly?**

**Comment by karrui** [comment]
Sorry I was not tracking issues for this repo and just looked at the issues! Thanks for opening, will be reviewing and fixing it!

**Comment by karrui** [comment]
Reset migrations in starter kit as part of the ticket to move to neondb instead of crdb
