### ISSUE TITLE
Session_secret env variable has trailing text on GitHub Codespaces environment

### ISSUE THREAD

**Issue by handshou** [opengovsg/starter-kit#165]
**Describe the bug**
In file `.env.development.local`, the session secret on GitHub Codespaces environment has a trailing `_least_32_characters` after the generated uuid.

Not a breaking issue, but may potentially cause some in future.

**To Reproduce**
1. Start a GitHub Codespaces environment by following starter-kit guide.
2. Open `.env.development.local`
3. Scroll down to SESSION_SECRET
4. See half of a random session secret with trailing `_least_32_characters`.

**Expected behavior**
A random session secret should be created without the trailing text `_least_32_characters`.

**Additional context**
Turns out its an un-updated script, postCreateCommand in `devcontainer.json` that needs to be updated.

The sed filter should be the following,
```bash
sed s/SESSION_SECRET=random_session_secret_that_is_at_least_32_characters/SESSION_SECRET=`npx uuid`/
```

Instead of 
```bash
sed s/SESSION_SECRET=random_session_secret/SESSION_SECRET=`npx uuid`/`
```

**Comment by karrui** [comment]
closed by https://github.com/opengovsg/starter-kit/pull/258
